language: java
jdk:
- openjdk12
services:
  - mongodb
sudo: false
addons:
  sonarcloud:
    organization: mylene-github
    token:
      secure: m7hlD3NAMBzsUO4ft2UxjbQrsCUSjIzPu9VL9ZM5HBtv9SVBdu10p2YK4VRkYClmwjhYQR2pMH80M/qWlgwObaj5nL7oNyjz4UzWmZLDulzXv8bfL/znxP536T2Q7GcKbdoMuBW9Pk7DtuCplGf16UVwtVuNRq7HfrrVprAS6M5hPKlGsfglD7KJ012Ei0MVLiCbPcc6cLov8DBvis1Sm3BOevRqCMGxhoRWzJUn76z00cHkucMtt/VlonN1u2rg0JdPhUJlA5eqYfvpjN0Sk0ApPSSk9AxTZ70werH39ZAt8g/tRcfdvyE+Ba3k6wT3xCnnPqLBasJanpAWz9f1kMF+Cacgwafmb3Fmw2CFZg3CKlhTyJqe2qAVNzAa/rlfxPmjJW24c+/jxShDshnlP98kVsDCyxwVuMn/7omh+8mzgB0z9bU9qglw78QhkhhaXLsbxpLhaE+tflizqMtnTiRM+yfI6/CFxW09WLUPNgNWgum2bcxM93FYs7q10H3wwl1clIMmwJmHRARgOw4aP5as3rbwKKpUjwttK/gp6ryydoOpLux7HeErgrcfq1O2tnxXvCtz2SgZSdKYIG6r1c8uczdKDcktDcIYyr5MRBfE7vb70Ma7EZU2tMm0PXTRBVfKMZ2jxMg2ni9IG8VUa2LEcPuY6DnpCa7OpuHsGl0=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  slack:
    secure: x2G88vs0qHX4FKKbLectqr9WEIW0AnQ1Y8fU+ytUAc6/U36ISMxu53XRx1BF1IdQIbG0bNrOk3sLEYEvLCOoPVDTp3oRS4XrGn3luLBbbI1e+4rlrzL80GGsQmn03OIgJFlaVmn3/p1OS0d31tD52SjhVIhXul4paSieZVgRv4JtZa4X/f19TfYqn6Xw7SzPAUHh+wP4nfrHqAVUp7Nbs30gcDaYG0DF+hp4Y0s1NINpfcz05ePvTcwXdhjplow/vYL8ZPbmn7faYBvdgJDorNeaZhs1lIOXzVxiPwSNAUVBLKb7nCfdTEh8ZIHUAoXjtuQsDldS3STUBpr+cTfchww7NsajU6tW0Trw4b8T5witCIQkL9fTzwYQx1Pk87RpOR6QISPvZxrgkot2kBvx2rx0H9pHCAMBBMTyTgjROX2vhsGO+Vh+LO9nHvcjpVhUFRvsAOfOarbS08yznXQkyVLZNmcUpQMsdpy3+KE64Dkymzn/cpySUUc9IVa+0PgzR/3e3WxFYd67hwQWY/JRSaSvw4u4mX7/8SHAXE3NVOyPHOYURo9iwM1IXSp8FxTiWiDucbTquaCt0BtbrWXAGnXdSQuJVvz6BrbsuO5A6Tt0TgO/NnGp0/MNkOxVufaeWqtgyC14wWgPEWrxcDyXRwPRTB4lfpFSXAbrYCwBLJk=


